### PR TITLE
Added build tag to readme

### PR DESCRIPTION
**Pull request by premsantosh**

### CODE REVIEW

**Comment by abrarsheikh** [comment]
fix it and ship it 👍

**Comment by premsantosh** [comment]
@abrarsheikh am not sure why it failed. I've only touched/updated the readme.
It says `The command "sudo mysql_upgrade" failed and exited`

**Comment by abrarsheikh** [comment]
@premsantosh try rerunning the build

**Comment by kdparker** [comment]
Reran, still has same error

**Pull request closed without merging**
